# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
          our_db_provider:
              entity:
                  class: AppBundle:Member
                  property: username
                  # if you're using multiple entity managers
                  # manager_name: customer

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check

    role_hierarchy:
            ROLE_ADMIN:       [ROLE_MEMBER, ROLE_VICE, ROLE_SECR, ROLE_VOCAL, ROLE_VOCAL, ROLE_TREAS, ROLE_BACK]
            ROLE_VICE:        [ROLE_MEMBER, ROLE_BACK]
            ROLE_SECR:        [ROLE_MEMBER, ROLE_BACK]
            ROLE_VOCAL:       [ROLE_MEMBER, ROLE_BACK]
            ROLE_TREAS:       [ROLE_MEMBER, ROLE_BACK]
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_MEMBER]

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user_menu, roles: ROLE_MEMBER }
        - { path: ^/user_menu/admin, roles: ROLE_ADMIN }

    encoders:
            AppBundle\Entity\Member:
                algorithm: bcrypt
                cost:      12

            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
                cost:      12
